### ISSUE TITLE
Franke function truncated

### ISSUE THREAD

**Issue by am-kaiser** [am-kaiser/CompSci-Project-1#11]
Can `Franke_and_biascorrection` be deleted? It looks like it is the same as `Franke`.

**Comment by harishpjain** [comment]
No we don't need it for the main code. But it's okay if its there, it was helping me understand the bias stuff better.

**Comment by am-kaiser** [comment]
But what is the difference (except that one of them also has the variance as an output)?

**Comment by harishpjain** [comment]
That is the difference. I wanted to see if I can use that variance to correct the bias. However, I still haven't figured that one out.

**Comment by am-kaiser** [comment]
Ok. Can't you use the same function and not use the variance output if you don*t need it?

**Comment by harishpjain** [comment]
Then when we unpack, we have to make sure to put a comma or else even the variance would be included when we don't want it. The franke_biascorrection is just for research purpose and will not be used for any results(as of now).
