### ISSUE TITLE
Catch overflow warning in sigmoid function

### ISSUE THREAD

**Issue by am-kaiser** [am-kaiser/CompSci-Project-1#6]
In stochastic_gradient_descent.py there is sometimes an overflow warning in exp(z) (sigmoid function). Using  
```
import warnings
warnings.filterwarnings("error")
```
is not possible in jupyter notebooks with widgets, At the moment I am using a blank exception
```
    try:
        return 1 / (1 + np.exp(-z))
    # If an overflow is encountered in exp the output is approximated with 0
    except:
        return 0
```
which is not good (Also not allowed by flake8).

**Comment by am-kaiser** [comment]
How do we (@antble, @harishpjain) handle the case when one value of X*beta is very big? Then exp(-value) is approximated with infinity. This happens roughly when the value is smaller than -745. I can catch the other cases like this:
```
# If z is bigger than 700 exp(-z) is approximated with 0 to prevent an overflow error.
    exponential = np.zeros((z.shape[0], 1))
    for elem_in, elem in enumerate(z):
        if -745 <= elem <= 745:
            exponential[elem_in, 0] = np.exp(-z[elem_in, 0])
        elif elem > 745:
            exponential[elem_in, 0] = 0
        else:
            print(z[elem_in,0])
            exit()
```
The biggest value if X is 4254. Therefore, it is very likely that the SGD code runs into this issue.

**Comment by harishpjain** [comment]
Why is the biggest value 4254? Aren't we normalising the data?

**Comment by harishpjain** [comment]
The parameters that we learn only works for normalised data because it was trained on normalised data. Largest value of X should be 1. 

Also, if beta values are large on the other hand then we have adjust the regularisation parameter i.e lambda to fix this. It penalises large value of beta.

**Comment by am-kaiser** [comment]
Yes you are right. I wasn't thinking properly yesterday. 

I changed the code to:

```
def sigmoid_func(z):
    """Calculate sigmoid function."""
    sigmoid = np.zeros((z.shape[0], 1))
    for elem_in, elem in enumerate(z):
        if -745 <= elem <= 745:
            sigmoid[elem_in, 0] = 1 / (1 + np.exp(-z[elem_in, 0]))
        elif elem > 745:
            sigmoid[elem_in, 0] = 1  # exp(-z) -> 0 if z-> inf
        else:
            sigmoid[elem_in, 0] = 0  # exp(-z) -> inf if z-> -inf and 1/inf = 0

    return sigmoid
```

**Comment by harishpjain** [comment]
Are we actually getting such values for X*beta? Is it because X is very high or beta is very high?

**Comment by am-kaiser** [comment]
Yes we do. It must be because beta gets big. The values of X do not get changed by SGD
