### ISSUE TITLE
Vectorisation of the code

### ISSUE THREAD

**Issue by harishpjain** [am-kaiser/CompSci-Project-1#8]
Vectorised python code runs much faster. For example, in normalise_data() function of logistic_regression.py, the values are normalised column wise in a for loop. This is possible in a single line without a for loop.

**Comment by harishpjain** [comment]
Check comments of normalise_data() and transform_0_1() for a vectorised form which should work faster. Needs testing though.

**Comment by am-kaiser** [comment]
Good idea. I could not use your code for normalizing the data because assume the column would consist only of the same value (i.e. [2,2,2,2,2]) then your code (and my previous one) produces nan as an output as the denominator is 0. I had to catch that with an if statement.
```
 for col in np.arange(1, matrix.shape[1]):
        denominator = np.max(matrix[:, col]) - np.min(matrix[:, col])
        if denominator != 0:
            norm_matrix[:, col] = (matrix[:, col] - np.min(matrix[:, col])) / denominator
        else:
            norm_matrix[:, col] = matrix[:, col]
```

**Comment by am-kaiser** [comment]
@harishpjain is it ok if I close this issue or do you have more recommendations on how to vectorize the code?

**Comment by harishpjain** [comment]
If the columns all have same values then it doesn't have an effect on the output right? Then we should not use that column at all for regression. But, yeah its not possible to normalise if its same. The if condition makes sense. 

However there is a tiny change that needs to be done if we use the code above. See the change below, we can't use the matrix values directly. 

else:
            norm_matrix[:, col] = 1.0

**Comment by am-kaiser** [comment]
Yes you are right. I changed that line.
